SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


DROP TABLE IF EXISTS `booktable`;
CREATE TABLE IF NOT EXISTS `booktable` (
  `ISBN` int(10) NOT NULL,
  `Title` varchar(20) NOT NULL,
  `EditionNumber` int(10) NOT NULL,
  `Author` varchar(50) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `booktable` (`ISBN`, `Title`, `EditionNumber`, `Author`) VALUES
(123, 'JAVA', 2, 'JEAN JACQUE'),
(456, 'C++', 3, 'FRANCOIS HOLLANDE'),
(145, 'HTML5', 1, 'GEORGE MAECHEL'),
(256, 'CSS', 2, 'JONY EDIT'),
(365, 'ORACLE', 3, 'WILL SMITH'),
(254, 'MYSQL', 1, 'ALAIN SAVARY'),
(541, 'C#', 2, 'CHARLE KIWI'),
(563, 'TOEIC', 3, 'CYRIL DANGO'),
(547, 'XML', 2, 'ALINE MAL'),
(569, 'RESEAUX', 1, 'FADOUA KRIRA'),
(587, 'TCP/IP', 4, 'SAN KRAWD'),
(589, 'CLOUD COMPUTING', 2, 'FIND BINJ');
